### ISSUE TITLE
Does this plugin work with AAP 2.5?

### ISSUE THREAD

**Issue by gojeaqui** [sabre1041/sabre1041.eda#5]
Hello,

I created a rulebook to use this plugin and it worked on AAP 2.4

But now on AAP 2.5, I'm getting this error:
```
** 2024-12-02 14:44:19.955998 [received event] *********************************
Ruleset: EDA | Cluster Events | Listen for newly created Services in EDA (aap) Namespace
Event:
Shutdown(message='Shutting down source: sabre1041.eda.k8s error : Could not '
                 'find source plugin for sabre1041.eda.k8s',
         delay=60.0,
         kind='graceful',
         source_plugin='sabre1041.eda.k8s')
```

I tried different Decision Environments but the result is the same.

**Comment by gojeaqui** [comment]
OK, I need to build a decision environment based on `de-supported-rhel8`, does anyone have an example containerfile?

I'm being able to sucessfully install `sabre1041.eda`, but now getting the error: `No module named 'kubernetes'`

**Comment by seadoox** [comment]
> OK, I need to build a decision environment based on `de-supported-rhel8`, does anyone have an example containerfile?
> 
> I'm being able to sucessfully install `sabre1041.eda`, but now getting the error: `No module named 'kubernetes'`

I am having the same issue so far.

**Comment by sabre1041** [comment]
I can test later in the week against AAP 2.5. 

However, does your DE have the `kubernetes` python module installed?

I'll post additional details as I work through testing later on

**Comment by seadoox** [comment]
Mine does have the kubernetes python module. I am using the ansible-automation-platform-25/de-minimal-rhel8:latest image as my base. I have added kubernetes, kubernetes.client, and openshift python modules. I have added sabre1041.eda and kubernetes.core galaxy collections. It is using python3.11. I had to have the build process add the openshift-clients rpm install to workaround this redhat issue - https://access.redhat.com/solutions/7024259

**Comment by sabre1041** [comment]
> Mine does have the kubernetes python module. I am using the ansible-automation-platform-25/de-minimal-rhel8:latest image as my base. I have added kubernetes, kubernetes.client, and openshift python modules. I have added sabre1041.eda and kubernetes.core galaxy collections. It is using python3.11. I had to have the build process add the openshift-clients rpm install to workaround this redhat issue - https://access.redhat.com/solutions/7024259

That is indeed a "fun" issue. After working through that process, are you still having issues or are still experiencing challenges?

**Comment by seadoox** [comment]
Yes I still have the same error that says no module named 'kubernetes' even though pip freeze shows it installed.

**Comment by sabre1041** [comment]
> Yes I still have the same error that says no module named 'kubernetes' even though pip freeze shows it installed.

ok. will look into it and follow up

**Comment by gojeaqui** [comment]
Hello, @seadoox @sabre1041 the `no module named 'kubernetes'` problem can be solved by adding this:
```
additional_build_steps:
  append_final:
# Esto hay que ponerlo por el bug: https://issues.redhat.com/browse/AAP-32856 (sino no se ve la libreria 'kubernetes')
    - ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.11/site-packages:/usr/local/lib64/python3.11/site-packages
```
To the `ansible-builder` source file

**Comment by gojeaqui** [comment]
Here is the complete `ansible-builder` source file I used to succesfully deploy the Decision Environment:
```
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/de-minimal-rhel8:latest'

dependencies:
  galaxy:
    collections:
      - ansible.eda
      - sabre1041.eda
  python_interpreter:
    package_system: "python311"
  system:
    - pkgconfig [platform:rpm]
    - systemd-devel [platform:rpm]
    - gcc [platform:rpm]
    - python3.11-devel [platform:rpm]

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  append_final:
# Esto hay que ponerlo por el bug: https://issues.redhat.com/browse/AAP-32856 (sino no se ve la libreria 'kubernetes')
    - ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.11/site-packages:/usr/local/lib64/python3.11/site-packages
```
